### PR TITLE
Parse addStoryType string value to boolean

### PR DESCRIPTION
**Pull request by dnsv**
YAML booleans are actually strings when retrieving them with `core.getInput()`, so they need to get parsed to a boolean value. 

I've applied a fix for the `addStoryType` input. It defaults to `true`.

### CODE REVIEW

**Comment by dnsv** [comment]
Hey @kuritz. Just saw that a new version of this repo was released and that it causes conflicts on all my PRs. Could you please let me know if you're interested in merging these, so I know if I should fix the conflicts or not.

**Comment by kuritz** [comment]
Hey @dnsv, sorry for that. The preference would be to open an issue first to discuss the change you want to make and then open PRs. We should add a contributing guide detailing that, so our fault for it being ambiguous.

I think this one is straightforward and we can get it merged ASAP. Thanks for proposing this. Can you update the tests to use string values as well in accordance with this discrepancy you pointed out? 

I'll take a look at the other ones now.

**Comment by dnsv** [comment]
@kuritz Thanks. I've resolved the conflicts and added a test. Existing tests don't need to get updated as they bypass the parsing by focusing directly on `getTitle()` and not `run()`.

**Comment by kuritz** [comment]
> Existing tests don't need to get updated as they bypass the parsing by focusing directly on getTitle() and not run().
Oh, I see. Thanks for pointing that out, i didn't not notice that!

**Review by kuritz — APPROVED** [review]

**Pull request merged**
